### ISSUE TITLE
Compile failure with GHCs not supporting `StrictData`

### ISSUE THREAD

**Issue by hvr** [jeffreyrosenbluth/wallpaper#4]
I noticed the following compile failure w/ GHC 7.10 and GHC 7.8:

```
Configuring component lib from wallpaper-0.1.0.1...
Preprocessing library wallpaper-0.1.0.1...

src/Types.hs:4:14: Unsupported extension: StrictData
cabal: Failed to build wallpaper-0.1.0.1 (which is required by exe:wallpaper
from wallpaper-0.1.0.1 and exe:rosette from wallpaper-0.1.0.1).
```

I've already revised the meta-data by adding

```
    other-extensions: DeriveFunctor, FlexibleContexts, OverloadedStrings, ScopedTypeVariables, StrictData, TypeSynonymInstances
```

which declares which extensions the compiler needs to support (w/o automatically enabling them) in order to prevent the cabal solver from selecting bad install-plans as well as giving better error messages on failures for the affected releases:

 - https://hackage.haskell.org/package/wallpaper-0.1.0.0/revisions/
 - https://hackage.haskell.org/package/wallpaper-0.1.0.1/revisions/

(note that the change-display is broken as it shows only a single `other-extension` having been added)

**Comment by jeffreyrosenbluth** [comment]
thanks
